# Generated by Django 6.0 on 2026-02-02 14:12

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='open_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcation', models.CharField(choices=[('depsoite', 'Deposite'), ('transfer', 'Transfer')], max_length=100)),
                ('account_nbr', models.CharField(default=user.models.account_number, editable=False, max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(default='abc', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(default='example123@gmail.com', max_length=254)),
                ('province', models.CharField(default='Lumbini', max_length=40)),
                ('city', models.CharField(default='kohalpur', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
